-- Dale Viaje: esquema completo para una aplicación estática con Supabase.
-- Ejecuta este archivo una vez en Supabase > SQL Editor > New query.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default 'viajero',
  city text not null default 'Granada',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  image_url text not null,
  location text not null,
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_likes (
  gallery_id bigint not null references public.gallery(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (gallery_id, user_id)
);

create table if not exists public.gallery_saves (
  gallery_id bigint not null references public.gallery(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (gallery_id, user_id)
);

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1), 'viajero'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.create_profile_for_new_user();

alter table public.profiles enable row level security;
alter table public.gallery enable row level security;
alter table public.gallery_likes enable row level security;
alter table public.gallery_saves enable row level security;

drop policy if exists "profiles are visible" on public.profiles;
create policy "profiles are visible" on public.profiles for select using (true);
drop policy if exists "users update their profile" on public.profiles;
create policy "users update their profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "gallery is visible" on public.gallery;
create policy "gallery is visible" on public.gallery for select using (true);
drop policy if exists "users publish own gallery items" on public.gallery;
create policy "users publish own gallery items" on public.gallery for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "users update own gallery items" on public.gallery;
create policy "users update own gallery items" on public.gallery for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users delete own gallery items" on public.gallery;
create policy "users delete own gallery items" on public.gallery for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "likes are visible" on public.gallery_likes;
create policy "likes are visible" on public.gallery_likes for select using (true);
drop policy if exists "users manage own likes" on public.gallery_likes;
create policy "users manage own likes" on public.gallery_likes for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users view own saves" on public.gallery_saves;
create policy "users view own saves" on public.gallery_saves for select to authenticated using (auth.uid() = user_id);
drop policy if exists "users manage own saves" on public.gallery_saves;
create policy "users manage own saves" on public.gallery_saves for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', true)
on conflict (id) do update set public = true;
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "public gallery images" on storage.objects;
create policy "public gallery images" on storage.objects for select using (bucket_id = 'gallery');
drop policy if exists "users upload gallery images" on storage.objects;
create policy "users upload gallery images" on storage.objects for insert to authenticated with check (bucket_id = 'gallery' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "users update gallery images" on storage.objects;
create policy "users update gallery images" on storage.objects for update to authenticated using (bucket_id = 'gallery' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'gallery' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "users delete gallery images" on storage.objects;
create policy "users delete gallery images" on storage.objects for delete to authenticated using (bucket_id = 'gallery' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "public avatars" on storage.objects;
create policy "public avatars" on storage.objects for select using (bucket_id = 'avatars');
drop policy if exists "users upload own avatars" on storage.objects;
create policy "users upload own avatars" on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "users update own avatars" on storage.objects;
create policy "users update own avatars" on storage.objects for update to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "users delete own avatars" on storage.objects;
create policy "users delete own avatars" on storage.objects for delete to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
